// <auto-generated />
namespace GestorTiendaInformatica.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class productoes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productoes));
        
        string IMigrationMetadata.Id
        {
            get { return "201902061011577_productoes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
